### ISSUE TITLE
Catch the filename in gcc handlers to have multi-file location list

### ISSUE THREAD

**Issue by gagbo** [w0rp/ale#1023]
Partly related to #985 (For the 'take care of the first matching group when appending to a location list" part)

As we see [here](https://github.com/w0rp/ale/blob/master/autoload/ale/handlers/gcc.vim#L103), the items added to location lists in ALE are not using the filename. The problem with this behaviour is that it becomes impossible to properly handle errors where the filename is actually different from the linted file. This is why we can't have a location list that will make us jump to the error/warning like Syntastic is able to do for example.

It would be nice to find a way to include the first match in gcc handlers in the ALE:items, so that the location list can be more precise and useful. To try and be more clear, I have created [basic tests](https://github.com/w0rp/ale/compare/master...Gagbo:loclist_multi-file_c_handling) to show what I mean and what I expect. They are not finished yet, and will be polished and completed for other linters once the main feature is done.

**Comment by w0rp** [comment]
Since that code was written, support has been added for adding filenames to loclist items. See issue #653.

The current code just throws away problems from other files, because that was the easiest thing to implement. Now the support for handling items with filenames for other files is in, parts of the code for C and C++ specifically can be re-written to support putting errors for other files in there.

**Comment by w0rp** [comment]
I'll put this down for the next minor version after this coming one.

**Comment by Gagbo** [comment]
I cleaned up the unnecessary "include handling" part and added the 'filename' key in gcc handler in a505311 , the only thing that needs polishing now is the part where sorting makes the output go in wrong order.

If you start ale with clangcheck on the test file in my fork, you'll see that the errors are sorted so that the suggestion for std:cout is put *before* the actual error in loc list (All the errors when opening vim come from clang_complete I think).
I think this comes from ale sorting because in the actual output from clang there's first the error and then the suggestion (in the asciinema, the first warning should be after the error, and the 3rd warning is from cpplint adding loclist items so it is not related to the first 2 coming from clangcheck)

https://asciinema.org/a/R8F3Mq3wgZksukKCiZf6aBNaA

**Comment by w0rp** [comment]
Be careful with the sorting. The problems ALE keeps in its loclist have to be sorted in a some known order in a generic way (not specific to any one linter) so that ALE will be able to perform a binary search on the loclist for displaying echo messages and balloons, and also for the benefit of loclist jumping.

**Comment by w0rp** [comment]
What I recommend is that if you have an error which has an occurrence in a file, and then originates from some other file, you could set the `'detail'` key instead, so you can see where the error might originate, or other information, with `:ALEDetail`.

**Comment by Gagbo** [comment]
The problem is more like the error in the output is actually 3 lines : 
- 'In file included from...'
- filename:l:c:error: 
- Perhape you meant this : and you have filename:l:c:note:

So the solution is either to always have the note just after the error in the loclist or (seemingly what you suggest) have the note as a 'detail' key from the actual error. The problem with this approach is that the possible declaration line is not jumpable if it's in :ALEDetail, while gcc/clang actually gives the location of the best candidate.

**Comment by w0rp** [comment]
See issue  #757. It may be possible to add support for jumping to errors from messages in the window there.

The items have to be sorted in some particular order, and I doubt it's possible to change the order for a case like this.

**Comment by Gagbo** [comment]
The basic implementation is done. The wanted behaviour is to take the whole text from the `filename:l:c:note:` line so that the user can see the path and line concerned by the info in `:ALEDetail`. 

This works fine in my testing if : 
- The 'note' from the compiler only concerns the most recent previous 'error' or 'warning' in the output (I'm pretty confident it is always the case)
- There aren't too many notes per error (because they are all dirtily appended)

I am still a little shy of deleting so much code that could be useful if I missed some behaviour we should support. Like having a gutter sign at the included line for these errors.

**Comment by w0rp** [comment]
The removal of the sign will take some consideration. I think we should try to keep the sign where the include is, if we can. There may be some good reason for removing it.
