### ISSUE TITLE
Want to use Pylint for python3..

### ISSUE THREAD

**Issue by ehzShelter** [w0rp/ale#103]
Is pylint supported ?

**Comment by w0rp** [comment]
Not yet, but if someone wants to open a pull request for it which works, I'll take that. If nobody else adds it, I'll add it eventually.

**Comment by neersighted** [comment]
Pylint has a bit of a ...difficult output format. Even when you manually make it something gcc-like, it likes to spit out multiline output with arrow pointers not unlike clang. We can't just drop those lines because the actual explanation is included there. I'll see what I can do, but it might be a while.

**Comment by w0rp** [comment]
One of the linters, I can't remember which one, handles that kind of output by looking for the markers every other line.

**Comment by neersighted** [comment]
The thing with pylint is it is only one some errors, not all of them. And the error message is split over the two lines, so we need to parse that and strip the arrow. It's... bleh...

**Comment by keith** [comment]
I've opened a PR for pylint support here https://github.com/w0rp/ale/pull/151

**Comment by ehzShelter** [comment]
Great..

**Comment by keith** [comment]
This is now is master!
