### ISSUE TITLE
Ale should run on filetype change

### ISSUE THREAD

**Issue by neersighted** [w0rp/ale#130]
When I manually `set ft`, I would like ale immediately to run instead of having to wait for another trigger.

**Comment by w0rp** [comment]
I wonder if there's an event we can use to watch for changes to the file type. There might be.

**Comment by neersighted** [comment]
Foetuinate that there is a `FileType` auto command, isn't it

**Comment by w0rp** [comment]
That should probably do it. I'd just try it, and see what the effect of running linting again every time the file type changes is.

It would probably be best to implement mapping buffers to jobs for the buffer and cancelling them based on the buffer number first. Otherwise you might end up in a situation where you run jobs for one file type, you change the file type, and then run the new linters without cancelling the previous ones.
