### ISSUE TITLE
Docker integration

### ISSUE THREAD

**Issue by toffi9** [w0rp/ale#1320]
Hi,

I wanted to integrate this with docker workflow, but I failed. I think because ALE right now it's not designed for that. Basically, I don't use virutalenvs anymore, and replacements for that are containers where are all of my python dependencies. Right now if I want to use flake8, mypy or some other linter I have to create virtualenv in my local environment, and pip install all requirements, which is redundant because I have also this all requirements in my docker container.

I tried `g:ale_command_wrapper`, but checking for executable is only searching in a local environment not respecting ale_command_wrapper. If I install, for example, flake8 in my local env it's then finding executable and runs commands in docker by `ale_command_wrapper`, but I have another problem because it injects current buffer absolute path to command, not relative path, because in docker container I have `folder/file.py`, and in my working directory I also have `folder/file.py`, but command injects `/Users/user/Projects/my_project/folder/file.py` and obviously I don't have this path in container.

Is there a way to work around this issues?

**Comment by w0rp** [comment]
This is a tricky issue. My recommendation is to run Vim itself inside of the Docker container if you can. The big problem you have to deal with is dealing with issues with paths. Vim wants to be able to create temporary files using an absolute path to the temporary file directory for many things. You need some absolute paths for files to check.

Generally I don't support this, because supporting it would drive me crazy.

**Comment by toffi9** [comment]
Ok, I understand. So I will stick with my virtualenv workflow, I saw also big problems with other plugins in vim, so I think this solution is good enough for me.

**Comment by w0rp** [comment]
If someone can come up with a solution for some better Docker support which won't change anything too drastically, I might merge that in. I just won't work on it myself.
