### ISSUE TITLE
Feature request: Add hooks for linting start/stop on a buffer

### ISSUE THREAD

**Issue by mrbiggfoot** [w0rp/ale#1363]
I'd like to have some indication when a linter is running in background, i.e. display file name in status bar in a different color or something similar. It would be nice if there was a possibility to register callbacks to be triggered when a linter starts/stops on a buffer. Then the users would be able to implement that sort of indication in those callbacks. The signature of the callbacks would be OnLinterStart(buffer_number, linter) and OnLinterStop(buffer_number, linter).

**Comment by Christian-Gibbons** [comment]
I believe something like this is already supported.  Check out the documentation for ALELintPre and it even has an example that changes the color of the statusline while the linter is running:
```
augroup ALEProgress
    autocmd!
    autocmd User ALELintPre  hi Statusline ctermfg=darkgrey
    autocmd User ALELintPost hi Statusline ctermfg=NONE
augroup end
```

**Comment by w0rp** [comment]
Yeah, that's the way to do it.

**Comment by mrbiggfoot** [comment]
Thanks for the responses!
Sorry, but that's not quite it... Say, I have "a.cpp" and "b.cpp" opened in adjacent windows. Say, I want to put a "@" sign in front of a file name that is being linted, and remove it when the linting is done. Ok, I can check the value of the current buffer in ALELintPre... but how do I find out which linter has finished in ALELintPost?

**Comment by w0rp** [comment]
The events can't pass on information like that, but I can give you something else to solve your problem. I documented `ale#engine#IsCheckingBuffer` and made it part of the public API. `ale#engine#IsCheckingBuffer(buffer_number)` will return `1` when ALE is busy checking a buffer, and `0` otherwise. You can use that in your window title functions to add an at sign, or whatever you want.

**Comment by mrbiggfoot** [comment]
Thanks a lot @w0rp, it seems to work! Will test it more and comment if anything pops up.

**Comment by damnskippy** [comment]
@w0rp is there an API that shows whether or not ALE has attempted to run a linter yet for a given buffer, or if ALE will not attempt to because there isn't a linter available for the given filetype, or linting is not applicable for the filetype?
Case in point: https://github.com/maximbaz/lightline-ale/issues/3#issuecomment-368560100

**Comment by w0rp** [comment]
I opened an issue for that here: #1379

**Comment by damnskippy** [comment]
Thank you!
