### ISSUE TITLE
Use lint from package.json?

### ISSUE THREAD

**Issue by kaihendry** [w0rp/ale#1423]
First off, thanks for Ale. When it works. It's a HUGE time saver.

## Information

NVIM v0.2.2
Build type: Release

Operating System: Archlinux

### :ALEInfo

https://s.natalian.org/2018-03-15/1521081033_2548x1398.png

How can I simply get :Aleinfo to dump to a file?

## What went wrong

Alefix didn't fix to the settings upon https://github.com/unee-t/frontend/blob/master/package.json

## Reproducing the bug

Clone https://github.com/unee-t/frontend.git

Introduce a standardjs in one of the JS files

Open file in vim with ale and expect it to auto fix it.

**Comment by w0rp** [comment]
I'm sorry, I don't understand your description of the bug. Are you saying that you tried to fix a file with `standard`, and nothing happened? Have you configured `g:ale_fixers`?

**Comment by kaihendry** [comment]
Sorry, I wasn't clear. First there is an issue with dumping Aleinfo to file ;)

Second, I know this is super lazy, but I want Ale to autodetect the project is using standard somehow so I don't have to configure ale_fixer..

**Comment by w0rp** [comment]
I understand now. You can use just `:ALEInfo` if the clipboard program isn't working, and that will print the info in Vim. You can copy and paste that instead.

The fixers can't be enabled automatically, unlike the linters. ALE shouldn't try to change any files without you telling it do that. Otherwise, ALE would annoy a lot of users. You could write [project configuration files](http://vim.wikia.com/wiki/Project_specific_settings) with `b:ale_fixers` variables in them to configure different fixers for different projects, or you could write some code into an ftplugin file, or you could use `g:ale_pattern_options` to configure different fixers based on the paths for files.

**Comment by kaihendry** [comment]
:ALEInfo runs into several pages for me. Would be nice if this could be dumped to file. Thanks!

**Comment by w0rp** [comment]
Yeah, that could make sense. I'll open an issue for it.
