### ISSUE TITLE
When multiple lints are found for a single line, warnings can overshadow errors.

### ISSUE THREAD

**Issue by Hnasar** [w0rp/ale#1426]
I have mypy and pylint running on with ALE, and if I have a given line with one pylint style warning, and two mypy type warnings, often the warning message is shown in the status line on the bottom of vim (is there a better word?) when I hover over the line.

The icon in the left gutter is a red >> to denote an error, but the status line text is of the warning.

I noticed that the status line text is always the one that occurs list in the location list, but can ALE somehow sort location list entries so the errors for a given line are always shown last, and are always shown in the status line?

My current workaround is :lopen and browsing for the line number but that's rather inconvenient.

Thanks for the great plugin BTW!

**Comment by w0rp** [comment]
Which problem you see depends on where the cursor is on the line.  Warnings nearer to the cursor on the left side will be shown, instead of errors further to the left. It will forever be that way. One thing that could be changed is showing an error instead of a warning if the column numbers for two problems are equal, including problems at column 0, for no column at all. That would require a small additional sequential search once the binary search finds a problem.

**Comment by liqing9399** [comment]
now，how to prompt for multiple errors in the same statement?

**Comment by w0rp** [comment]
Your best bet is to use `:lopen` and look at the loclist to see all of the problems.

**Comment by liqing9399** [comment]
thank you!
