### ISSUE TITLE
Feature request: Completion for flow

### ISSUE THREAD

**Issue by trevordmiller** [w0rp/ale#1457]
Would be sweet if [Completion](https://github.com/w0rp/ale#usage-completion) - `h ale-completion` - worked for flow as it does for typescript. Specifically:
- `g:ale_completion_enabled`
- `g:ale_completion_delay`
- `g:ale_completion_max_suggestions`

p.s. thanks for adding this for typescript, it is very helpful!

**Comment by w0rp** [comment]
This issue is closely related to #1458.

I have implemented completion support for Language Server Protocol _almost_ already, using the Python language server for testing. There's just a little bit more work that needs to be done for getting it working. In the future, I'd also like to consider adding support for integrating with [deoplete](https://github.com/Shougo/deoplete.nvim) too, which probably does a better job of managing this kind of thing. I still want to have some basic support for completion without having to install another plugin an so on. The built-in support doesn't have to be perfect.

**Comment by w0rp** [comment]
#1703 Added support for flow-language-server, and this satisfies that.
