### ISSUE TITLE
Use NPX for npm based linters?

### ISSUE THREAD

**Issue by ycmjason** [w0rp/ale#1554]
Currently ALE seems to be looking for the correct linters executables from `node_module`, would it be nicer if we just use `npx` and let `npx` decide where to load the binary?

**Comment by w0rp** [comment]
The is the first time I've heard of `npx`. I'll look into it.

**Comment by ycmjason** [comment]
The advantage of using `npx` is that it will try look into local modules, if not it will look for global modules. This makes things maybe a little bit easier and more flexible.

**Comment by ycmjason** [comment]
I guess one problem is `npx` will download the module and use the module only once. This might be problematic?

**Comment by w0rp** [comment]
#2183 started looking at doing this only for the `bash-language-server`, but I closed that PR for now. I think it would make sense to add support for running various linters via `npx` in general, probably after. Maybe after implementing #2132.

**Comment by jasonkarns** [comment]
Personally, I don't think I'd want ale using npx. I'd want it to be using the locally installed module, and if it's not locally installed, to use the globally installed one. If it's not installed locally nor globally, it'd want ALE to error out rather than have npx install the module "just once". Since ale is going to be running frequently, I'd want to be immediately and loudly notified that the necessary bin is missing; not have that error masked by npx temporarily installing it for me.

**Comment by w0rp** [comment]
It's a matter of preference. I think it makes sense to add support for it, for those who want it.

**Comment by ycmjason** [comment]
I think I kind of agree to @jasonkarns now. I am not sure why I thought it was a good idea to use `npx`.

**Comment by w0rp** [comment]
Okay then, I'll close the issue.

**Comment by gte620v** [comment]
How I am supposed to use prettier or other npm-installed linters/fixers now?  Since upgrading to the latest npm (6.14.4), `prettier` is no longer in the path even when I do a global install via `npm install -g prettier`, so when ALE tries to run `prettier`, it fails.  Running `npx prettier` works fine, but ALE isn't wired to do that.

I understand that the preferred way to run the binaries in `.node_module/.bin` is to prefix the command with `npx` now: https://stackoverflow.com/a/45164863/5058588

I have the same problem with ESLint.  Their install page explicitly says that ESLint is run with `npx eslint`: https://eslint.org/docs/user-guide/getting-started

@ycmjason or @jasonkarns can you point me to your workaround?  I see no obvious way to make prettier work with ALE.  (full disclosure, I am an npm/node noob).
