### ISSUE TITLE
Automatically detect if `pipenv` should be used for linters

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#1656]
First mentioned in a comment for #1629

`pipenv --venv` will print information that can be used to check if a file is instead of a `pipenv` managed project or not. If a file is in such a project, ALE could automatically load executables from `pipenv` projects instead. This `pipenv` detection ought to be configurable, and probably off by default, as not everyone will be using `pipenv`.

**Comment by klardotsh** [comment]
@elebow Any hopes of you opening a PR of that branch to upstream here?

Additionally, it'd be nice to support [poetry](https://github.com/sdispater/poetry) in a similar way (running literally works the exact same way - `poetry run flake8` or whatever). The goofiness is that `poetry` is hyper-aggressive in creating venvs for you - as far as I can tell, the safest way to check for poetry existing is to stat `pyproject.lock`. I've opened a feature request in that repo to address this.

**Comment by klardotsh** [comment]
Well, I see @elebow's commit actually checks for a lockfile the same way I considered doing for poetry, so maybe that's a sane route to go down (and has fewer upstream dependencies...)

**Comment by w0rp** [comment]
Thanks to @elebow, you can now use pipenv for the Python linters if you set `g:ale_python_auto_pipenv` to `1`, or any of the various options for each specific linter.

**Comment by cmcaine** [comment]
You haven't set a default value for this variable and vim is giving:

E716: Key not present in Dictionary: ale_python_auto_pipenv

**Comment by elebow** [comment]
I thought that was covered by https://github.com/w0rp/ale/commit/169a6e26b2ca63ab0f2f5bb3d2176ff0a2f68bc3#diff-a5941a5354db7e7a717f0be61ffc56bdR4, but I see that you are right.

It seems `autoload/ale/python.vim` is being loaded after the `ale_linters/python/*` files. But setting the variable in `autoload/ale.vim` results in the correct behavior. I'm having trouble determining the load order of files because an `echom` in `ale_linters/python/*` doesn't seem to have any effect, but it appears that the load order is (in relevant part):
1. `autoload/ale.vim`
2. `ale_linters/python/*`
3. `autoload/ale/python.vim`

I'm not sure whether this is intentional, but I would suggest that `autoload/ale/python.vim` ought to be loaded before the individual linter files if possible.

If that's not possible, then I suppose the obvious fix is to set the variable in `autoload/ale.vim` or some other file that is loaded early. Or just at the top of each individual linter file, though it's an inelegant solution.

**Comment by kctong529** [comment]
Adding the line `let g:ale_python_auto_pipenv = 1` and `let pipenv_venv_path = system('pipenv --venv')` to `~/.config/nvim/init.vim` does not make any difference for me. When I open a `.py` file in nvim, ALE shows `[pylint] Unable to import ...`.

`$ pipenv run python` and `$ python` are showing different import message, so I believe it's not a problem caused by pipenv itself.

**Comment by w0rp** [comment]
Open a new issue with the output of `:ALEInfo`, so others can look at the output of that.

**Comment by LeonardMH** [comment]
@kctong529 I was also having this issue, make sure you have an applicable linter installed **inside** your pipenv virtual environment, it won't see your globally installed linter.

I have and pylint installed globally but it was not installed in my virtualenv, and no other linters we available, `:ALEInfo` helped me narrow this down to pipenv choking on one of the linters (mypy I think). So for example I fixed this with `pipenv install --dev pylint`.
