### ISSUE TITLE
Consider using `rustc --emit metadata` by default

### ISSUE THREAD

**Issue by w0rp** [w0rp/ale#1684]
See #1031

`-Z no-trans` only works with `nightly` Rust versions. `--emit metadata` doesn't generate a binary, and might work in more versions. Someone should find out which versions of Rust support that option and consider using that option by default. The default shouldn't be changed until we know that it's safe to do so.

**Comment by mandeep** [comment]
I believe `-Z no-trans` no longer works even on nightly. ``--emit=metadata`` was released back in version 1.16.0 IIRC. Since 1.16.0 was back in early 2017, I think it would be okay to default to ``emit=metadata`` but I'd like to hear what others have to say.

**Comment by w0rp** [comment]
Okay, thank you for the information.

**Comment by jpsouzasilva** [comment]
Running on stable, a small/annoying aspect of `--emit=metadata` is that it will still generate a metadata file from wherever you're spawning your Vim session.

So if you type (from `/home/[your_username]`):

`~$ nvim ~/rust/my-little-project/src/main.rs`

It will generate a `/home/[your_username]/librust_out.rmeta` file. In my case it's empty since the project is just a starter one with no external crate dependencies.

There is an [issue open at /rust-lang](https://github.com/rust-lang/rust/issues/52661) for adding support to `--emit=nothing`, which would probably be the appropriate case here (rustc is only used as a linting tool and doesn't need to generate code).

Until then, **if you're on stable and plan to swap this flag in**, please be aware of this side-effect. It's still much better than generating binaries with no flags on, but still not the desirable effect.

**Comment by w0rp** [comment]
The `rustc` linter now uses `-Z no-codegen` by default, and people on older versions can change their options appropriately.
