### ISSUE TITLE
Golang Language Server support

### ISSUE THREAD

**Issue by esn89** [w0rp/ale#1822]
At the moment, there doesn't seem to be support for the go-langserver.  Only for type script, can we please add in support for Go?

**Comment by Carpetsmoker** [comment]
Adding it shouldn't be very hard, since the entire point of LSP is that there is one protocol for all languages.

You can use something like #1783 to help you get started.

**Comment by w0rp** [comment]
It's really just a matter of telling ALE which command to run, where the project root is, etc.

**Comment by wavded** [comment]
I updated go-langserver and that issue no longer exists so must have been an issue there.

**Comment by esn89** [comment]
I have this set up in my init.vim:

```let g:ale_python_pyls_executable = '/Users/evanng/Library/Python/2.7/bin/pyls'
let g:ale_go_langserver_executable  = '/Users/evanng/.go/bin/go-langserver'
let g:ale_linters = {
\   'python': ['pyls'],
\   'go': ['golangserver'],
\}
let g:ale_python_pyls_use_global = 1
let g:ale_completion_enabled = 1
```

However, when I try it out on something like "fmt.P" (i expect a menu to pop out) nothing does.

Am I doing something wrong?

**Comment by wavded** [comment]
After trying to get some actual work done with go-langserver (running latest master) and ALE, I can say that it is so slow and blocks on every character that it is pretty much unusable. Have others experienced this?

**Comment by Carpetsmoker** [comment]
The current state of completion for Go is a bit of a mess @wavded:

- go-langserver uses gocode for completion.
- nsf/gocode works great for many years. It relies on the compiler cache in the `$GOPATH/pkg` directory.
- There have been major overhauls in how Go compiler caching works starting in Go 1.10 and continuing in Go 1.11. This has broken nsf/gocode for most practical purposes.
- nsf does not have the time to update gocode, and has declared it "deprecated".
- As a response mdempsky/gocode was created, which scans the source tree instead of using the compiler cache
- This is very slow (and your problem, as [go-langserver enables this by default](https://github.com/sourcegraph/go-langserver/blob/master/langserver/completion.go#L55)).
- There has been some work improving the gocode cache, but that PR has been sitting without updates for a while, and mdempsky hasn't been active in a few months.
- In the meanwhile, nsf has returned and updated the original gocode to work again.
- I believe there is also a third version now. I kind of lost track here.

This is a problem all editor/IDEs struggle with at the moment AFAIK, as they all rely on gocode. This isn't really something ALE can fix, and AFAIK there is no "quick fix" other than:

- Disabling "completion as you you type" (and only do it on e.g. Tab). It'll still be slow, but won't slow down typing etc.
- Disabling completion from source, which means it won't work for a bunch of cases.

Other than that you're going to have to wait for a new/fixed gocode version.

**Comment by wavded** [comment]
Thanks for the detailed explanation @Carpetsmoker, makes sense. For whatever reason it is fast for me now (only thing I did was remove `vim-go`).  So will roll with that for now :)
