### ISSUE TITLE
How to ignore specified warning？

### ISSUE THREAD

**Issue by dcy** [w0rp/ale#1868]
In syntastic:
```
"let g:syntastic_quiet_messages = { 'regex': ["should have comment or be unexported"]}
```
How to do it in ale?

**Comment by w0rp** [comment]
For ignoring messages, you should configure each tool individually, through either configuration files or by changing the options for a linter.

**Comment by dcy** [comment]
Is there an example?

**Comment by w0rp** [comment]
You can use different settings for each linter.

https://github.com/w0rp/vim/blob/df44e61a2e72442f0b1e59a67052da2b8447939d/ftplugin/gitcommit.vim#L2

Otherwise, create a project configuration file for each linter, such as [one for ESLint](https://eslint.org/docs/user-guide/configuring).

**Comment by w0rp** [comment]
See `:help ale` for a table of contents linking to all of the options available for everything.

**Comment by dcy** [comment]
I don't know how to configure it to ignore the specified warning, It's golint's warning.

**Comment by w0rp** [comment]
Consult the documentation for `golint`.

**Comment by w0rp** [comment]
That isn't relevant to this issue, but thank you.

**Comment by sdeleon28** [comment]
I think that I have a valid use-case for this feature.

My team's `.eslintrc` includes the `import/no-unresolved` rule. I get false-positives from ALE (because it can't figure out the package dir properly?). My other teammates use other editors/linters, so I can't remove it from `.eslintrc` because it would disable it for them also.

I would like to ignore the rule in my local setup so I don't get errors everywhere. Some hook that allowed me to `grep -v 'import/no-unresolved'` before entries are added to the location list would be super useful in this case.

**Comment by w0rp** [comment]
You should configure ESLint so it does work, or is submit a patch for the ESLint plugin or in ALE so it works. I do think filtering the list of problems in Vim is a bad idea. If we did do it, it would be best to do it with a function that returns `0` or `1`.

**Comment by wasowski** [comment]
Unfortunately, lacheck cannot be configured to filter. At least not without writing a wrapper for it. For now I just disabled it entirely :(
