### ISSUE TITLE
Autocomplete doesn't suggest method names in languages that don't use . for members

### ISSUE THREAD

**Issue by ngavalas** [w0rp/ale#1904]
When using the LSP with Hack (or any language that doesn't use `.` to access member functions, like Rust with `::` for modules), ALE doesn't autocomplete the available functions/members. You need to guess the first character of the method you want to call, type that, and then ALE properly shows all of the available autocomplete entries starting with that character. LSP implementations usually support this type of autocomplete.

For a concrete example, in Hack (running the `hh_server` LSP implementation), if I type `FooClass::`, I'd expect to see all of the available static class variables/methods/constants available on `FooClass`. If I manually send an LSP query at that position, the response correctly has that information.

**Comment by thenewvu** [comment]
Hello @w0rp, currently, ALE doesn't trigger completion on variables that their type is a pointer in C because its trigger character is `->`. I've been looking for a solution for this and turned out there's no way to customize `s:trigger_character_map` at https://github.com/w0rp/ale/blob/01331266a84859d4b0935b81ae773ff0d7af7522/autoload/ale/completion.vim#L63

Could you consider to introduce a `g:trigger_character_map`?

**Comment by w0rp** [comment]
What is should do is read the trigger characters from the language server, and that map should be replaced with what the language server says is valid instead.
