### ISSUE TITLE
Gometalinter has no output for wildcard

### ISSUE THREAD

**Issue by zobrien** [w0rp/ale#1974]
I'm new to go (previously a Java developer). I've installed gometalinter and have it running on a "hello world" type project (bowling scores). And i'm not receiving any output unless I run gometalinter against a single file. 

File structure:

```
myProject
    -> examples
        -> example_functions.go
        -> example_functions_test.go 
```
```
$ pwd
...Stuff.../myProject/examples

$ gometalinter example_functions.go
example_functions.go:68:26:warning: func (*Game).rollMany is unused (U1000) (megacheck)
example_functions.go:73:26:warning: func (*Game).rollSpare is unused (U1000) (megacheck)
example_functions.go:77:26:warning: func (*Game).rollStrike is unused (U1000) (megacheck)

$ gometalinter ./...
# pauses for processing and then returns nothing
```

**Comment by w0rp** [comment]
Okay, what's the bug in ALE? Include the output of `:ALEInfo`, explain what went wrong.

**Comment by Carpetsmoker** [comment]
`gometalinter example_functions.go` probably errors out as those `rollMany` etc. functions are used in another Go file, so if you're only checking that one file it appears "unused" to gometalinter.

As w0rp mentioned, this doesn't seem like an ALE problem? I'll close this for now due to lack of feedback. Feel free to comment if you have further problems or questions and we can reopen this issue.
