### ISSUE TITLE
Question: Stack Exchange recommendation

### ISSUE THREAD

**Issue by benknoble** [w0rp/ale#2115]
In reference to: 146769c61671ebfb25cc7efd7acdc35a6a1d33da

Has the ALE community discussed with the vi.stackexchange community (of which I am also a member) this type of recommendation? Are there meta posts that can be linked to describe the decision surrounding this recommendation, what's on & off topic specifically with regards to ALE, etc.? (A [quick search](https://vi.meta.stackexchange.com/search?q=ale) reveals, alas, the answer is _no_.)

The commit came as a surprise to me, though I monitor vi.stackexchange pretty closely. It seems like we should be more intentional with how we interact with that community, especially since we already get a number of questions there that are more easily answerable by plugin maintainers and communities (and we often redirect them to the Issues tracker of Github repos).

Also see this [help center article](https://vi.stackexchange.com/help/on-topic) about on-topic-ness, from where I draw the following quote:

> Questions about Vim plugins are on topic but be aware that bug reports and feature requests for a plugin would be better off in that plugin's issue tracker. Most of the plugins available on Github use the built-in issue tracker. (The "Issues" tab in the top menu.)

---

Part of the diff:

```
Are you having trouble configuring ALE? You should ask tech support style
questions for ALE on [https://vi.stackexchange.com/](Stack Overflow) or perhaps
on [Reddit](https://www.reddit.com/r/vim/) instead. GitHub issues are for
reporting problems with software, not for tech support.
```

In fact, I would argue that vi.stackexchange (and just about every other vim plugin on github that I know of) encourages and expects GitHub issues to be used for engaging with the dev community to ask questions about the software: if ALE maintainers would feel better with an FAQ/Wiki, a dedicated Q&A site, or some other mechanism, I recommend they take the time to create one, rather than shunt their problem onto others.

I at vi.stackexchange am _also_ not for tech support.

_P.S._ The markdown link syntax in that commit is backwards to my eyes.

**Comment by benknoble** [comment]
Related: [Meta Question](https://vi.meta.stackexchange.com/questions/1463/does-vi-stackexchange-want-tech-support-questions-from-ale)

**Comment by w0rp** [comment]
No, I just thought it would be a good idea. I don't think people who maintain plugins should be answering questions simple about how to use the plugin, like, "How do I get flake8 installed?"

The GitHub issue tracker should be used only for reporting bugs and for feature requests. This can include requests for better documentation. I receive a large volume of emails, and I would prefer to see only bug reports and feature requests if possible. I think Stack Exchange is a much more appropriate place to ask questions about how to use software.

**Comment by benknoble** [comment]
"How do I get flake8 installed" is still off topic for vi.stackexchange, where the discussion is ongoing. 

How you manage your issue tracker is up to you; I would suggest that funneling users to vi.stackexchange be worded carefully, done with input from that community.

**Comment by chrisbra** [comment]
FWIW: I maintain a similar popular vim-plugin [vim-airline](https://github.com/vim-airline/vim-airline/) and a lot of usage questions are coming around that I have to manage mostly myself. And as a member of the vim community (both vim-dev and vim-use mailinglist), reddit and stackexchange I don't appreciate that ale questions are redirected there, sorry. In my opinion, questions regarding the usage of your plugin should be answered here or at your wiki or create a separate google list for that.

**Comment by chrisbra** [comment]
Don't get me wrong, I think it is perfectly okay to send people to other vim forums for general usage questions, like how do I need to set a variable, how do I configure Vim, etc. But please do not expect people at those forums to know about your plugin and how to configure it properly. That is most likely not the case and honestly, 6000 people starring this plugin should be a big enough community to be able to chime in here for usage questions on the plugin. I know that is usually not the case (as I can see it on the vim-airline bugtracker).

**Comment by w0rp** [comment]
Questions about how to configure ALE only belong in the ALE GitHub issue list of configuration is either impossible or needs improvement. Only bug reports and feature requests belong in bug trackers. Tech support does not belong in a bug tracker.

I want people to be able to get the answers they need for how to set up a plugin, and if there's no one available on GitHub to answer their questions, it's bad for them. Advising people to ask for help on Stack Exchange or Reddit is an obvious choice. I'm going to set up a Gitter, or something similar, so people can get additional help. I need to reduce the volume of emails I receive so I can focus only on bugs and new features.

**Comment by gagbo** [comment]
The issue is that it creates a lot of noise in the issue tracker, for not much added value.

I don't understand how it is a problem to have basic questions about vim // usage being redirected to SE, where search engines will help you find the answers quickly for these common questions.

In my opinion, the FAQ option is not really going to work well either, since most of the users we see asking questions do not check `:ALEInfo` output, although it is stated in plugin [doc](https://github.com/w0rp/ale/blob/0d14380d8a246ac749ef15e9b5c481e3639588ac/doc/ale.txt#L521), although maybe not "blatant/full-caps/first-line" enough

**Comment by chrisbra** [comment]
> I don't understand how it is a problem to have basic questions about vim // usage being redirected to SE, where search engines will help you find the answers quickly for these common questions.

As said before, I am not arguing against that. That is perfectly okay and I certainly also do it with the questions we receive at the vim repository or at the vim-airline repository. What is not okay, is to send people with questions regarding your plugin away.

**Comment by w0rp** [comment]
I think it's perfectly fine to send people to a more appropriate place for asking for help, and Stack Exchange is very appropriate. It's a well-formatted question and answer site with a wide range of users willing to help.

**Comment by gagbo** [comment]
> What is not okay, is to send people with questions regarding your plugin away.

When it is put like that, it seems that contributors just want to have fun by themselves and kick everyone else away. This is not the case.

The whole point of SE for me is that when I search Duck Duck Go for a question and it happens that one result matches on this domain I automatically get the accepted answer in my browser. Without having to ask a question and wait.

When it comes to "tech support", I like 2 things : 
# Archiving
- Issues on github are opened and closed ; and by default when you search issues you only search for opened issues (since this is a development website)
- Questions on SE-style website are archived but still easily searchable : Actually questions which have been answered are *promoted* in the UI since this is what you want : answered questions about usage.
- Terrible to do with any chat-based solution (IRC or Gitter or Slack or whatever) ; because the questions will get asked an infinite number of times.

# Searching
- Issues on github are terrible to search through when looking for answers.
- Questions on SE are made to be found : when you have an issue like "how to suppress ESLint warningX in ale ?", all search engines are more than happy to help you find the answers there.
- Still terrible with any chat-based solution

StackExchange is just the better platform for this kind of questions. We can argue about FAQ solutions for this, but : 

- if the URL of the FAQ is in the README.md or in ALE docs, I'm pretty sure users will still reflex-open issues for their questions instead of going to the FAQ.
- A big FAQ is terrible to search through.

Maybe a FAQ about how to read and understand correctly the output of `:ALEInfo` would help, but even then, I am quite pessimistic about the count of actual visits this page would get vs. "I'm already on Github, I'll just open an issue !"

**Comment by w0rp** [comment]
I made the language a little friendlier just now, so people don't get the wrong idea. I'll see how hard it is to open a Gitter now too.

**Comment by benknoble** [comment]
Based on comments from Meta, vi.SE is not entirely against questions about ALE, but they will need close monitoring to make sure they remain high-quality and on-topic. We also don't want a flood of duplicate questions, although as mentioned SE's search features help this.

I personally appreciate the new wording, and I think a Gitter will help alleviate GitHub flooding while supporting a community discussion that doesn't fit well with the model on SE sites.

**Comment by w0rp** [comment]
Okay, thank you. I hope people can find the help they need in the appropriate places, and I'm sorry if I caused any confusion.

**Comment by Carpetsmoker** [comment]
I posted an answer on the [meta question linked above](https://vi.meta.stackexchange.com/q/1463/51), but I'll reproduce that answer here since not everyone may follow that. The text is written from the perspective as a SE user, so "here" refers to vi.SE, not GitHub or ALE.

---
---

Personally — speaking as a member of the community, and not a moderator — I don't really see a problem with this.

This site is an appropriate platform for asking technical questions, including questions on how to use a plugin. We [already have a few questions about ALE](https://vi.stackexchange.com/questions/tagged/plugin-ale), and at a glance most of them seem okay.

This is a fairly small site with a low influx of questions every day; we can always re-evaluate *if* it becomes a problem (I don't expect it will).

A lot of the problems that happened on Stack Overflow are because companies/projects that were redirecting to Stack Overflow were either completely off-topic (e.g. hosting providers), or communicated it in such a way that implied that *all* support questions could be asked there, including non-programming ones. I don't really see these problems here.

Some people have since taken this as a "never redirect to Stack Overflow", but in general it's not an issue. Sure, people following a "ask tech questions here" links can ask bad questions, but so do other people. I'm not sure if there is a strong correlation.

---

I'd also like to add some background to the above: in my experience maintaining a popular Vim plugin can be a frustrating experience, even more so than maintaining open source projects in general.

A *lot* of issues on the bug tracker are very unclear and posted by people who, frankly put, have no idea what they're doing. They don't know Vim; they don't know the language they're working with; they don't know Unix/Linux basics. You really have to take them by the hand and guide them.

Don't get me wrong, it's not that I mind helping people out who are new to Vim and confused — I think my contributions here are proof enough of that — but there's a time and place for everything, and while I don't mind *in general* to guide new people along, I don't want to spend my entire waking life doing so. Sometimes I just want to talk to people who know what they're doing. When I contribute to open source I am, for the most part, [just DIY-ing](https://arp242.net/weblog/diy.html). Back when I was more active in maintaining vim-go half the time I was helping people make sense of basics such as GOPATH, and it wasn't fun.

You typically don't get a whole lot of long-term help with maintaining software projects. Sure, there are people who drop by and contribute a few patches, but people who consistently do the "gruntwork" over a long period of time are rare. In the specific example of ALE it's mostly just w0rp  (I planned to do a lot more work on ALE, but stuff happened that made me end up in New Zealand, and now I don't have a lot of time, I still hope to work on it *Soon*™).

So if "offloading" some of the maintenance burden to this site makes life easier for w0rp, then I don't see why not? I know some people have a rather purist view of what Stack Exchange should and shouldn't be, but I am not one of them. There are limits, but as mentioned, general questions about Vim usage (including plugins) have always been on-topic since this site was started, and as long as the questions are useful, answerable, and not wildly off-topic I don't see what the problem is with a plugin linking to us.

**Comment by w0rp** [comment]
Thank you for your detailed comments. I think your thoughts largely mirror my own.

I really do appreciate all of the help that people across the world give both to the ALE project, and across many free software projects in general. Every day I find new reasons for my confidence in free software and the general ability of people to be rational and arrive at better outcomes for everyone involved.

I hope everyone can get the help they are looking for, and I hope that I personally, and others, can make some more meaningful contributions to ALE before very long.
