### ISSUE TITLE
Gitgutter is overwritten by ale

### ISSUE THREAD

**Issue by Shookit** [w0rp/ale#23]
When using the gitgutter plugin, which adds git changed/added/removed annotations to the left gutter, ale seems to be in competition for the gutter space. I see gitgutter's annotations flash briefly, and are then overwritten when ale finishes processing with either nothing, or with whatever syntax issues ale found.

**Comment by w0rp** [comment]
I've never used gitgutter myself. I wonder if this plugin can be made to be
compatible somehow. I might look into this a little later. It might be a
simple matter of making one plugin or the other only clear particular types
of signs, or remember which signs were set to clear them again.

**Comment by Shookit** [comment]
Yeah, I wouldn't normally raise the issue, but it's a fairly popular plugin, so I figured it would be worth bringing up

**Comment by w0rp** [comment]
Nah, always raise issues. Otherwise nothing gets fixed. Thank you for
letting me know. :+1:

**Comment by KabbAmine** [comment]
If I remember well, vim allows only one sign in the gutter, so its quite hard to make those kind of plugins work together.

**Comment by prashcr** [comment]
Similar issue with Syntastic and gitgutter: https://github.com/airblade/vim-gitgutter/issues/1

The agreed solution in gitgutter was to avoid writing to a sign when a sign already exists, thereby effectively letting Syntastic (and ALE) take preference.

The main issue now is that ALE deletes the entire sign column every time https://github.com/w0rp/ale/blob/master/plugin/ale/sign.vim#L35

Instead, it should only find and delete `ALEWarningSign`  or `ALEErrorSign`, like gitgutter does, so that lines that aren't being used for lint errors can still display diff or other symbols https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/sign.vim#L13

**Comment by w0rp** [comment]
For now, you can disable the ALE signs if you only want to see the
gitgutter signs. There's a global variable you can set to `0` in your
vimrc, written in the flags file.

**Comment by deathmaz** [comment]
I noticed that error signs stoped to dissapear:
https://asciinema.org/a/7zxbqvad07iyf5f151s9bjc4y

**Comment by Shookit** [comment]
Just gave it a try, everything looks great on my end!

**Comment by w0rp** [comment]
@deathmaz Did I introduce a bug with it not clearing signs, perhaps? Try pulling the latest code and see if the signs are ever removed.

I'll let the dust settle on this issue a little until everything seems to be working well.

**Comment by deathmaz** [comment]
Everything works fine after update 👍 
Thank you!

**Comment by tonglil** [comment]
Is ale signs suppose to overwrite git signs?

I am using https://github.com/mhinz/vim-signify, and also tried https://github.com/airblade/vim-gitgutter.

**Comment by w0rp** [comment]
ALE is supposed to avoid removing other signs if it can. I suppose it could display over top of other signs. If you have a specific issue, open a GitHub issue for it, and I or someone else can take a look. There are a few documented options for changing the IDs ALE uses for signs, in an attempt not to conflict with other plugins. ALE parses `:sign place` output to try and identify its signs when removing signs, rather than clearing everything.
