### ISSUE TITLE
[Feature request] - Add support for xo

### ISSUE THREAD

**Issue by Torwori** [w0rp/ale#267]
https://github.com/sindresorhus/xo
https://github.com/sindresorhus/vim-xo

**Comment by w0rp** [comment]
I'll support whatever works. I don't think we should use `vim-xo`, but just add a new linter file to the project here. Maybe there is a good reason to do that. That would involve adding ALE support to that plugin, rather than the other way around.

I submitted an issue to `xo` which mentions something which is very useful for ALE: https://github.com/sindresorhus/xo/issues/175 That might be useful for others.

**Comment by w0rp** [comment]
The linter for has been added already.
