### ISSUE TITLE
Non-deterministic test failures on vim-v8.0.0027 for test_command_chain.vader

### ISSUE THREAD

**Issue by lucaskolstad** [w0rp/ale#413]
This issue tracks the non-deterministic test failures noted in pull requests #411 and #409.

On Arch Linux I can locally reproduce with:

```bash
git clone https://github.com/w0rp/ale
cd ale
make test # if successful, keep running a few more times
make test
make test
....
```

Eventually one test case fails for me non-deterministically but only in the case of `vim-v8.0.0027` and never for `vim-v8.0.0000`. I have a failure on 5 / 10 runs. The only test case I can reliably reproduce failure on, and the one seen in PR #411, is copied here:

```
  Starting Vader: /testplugin/test/test_command_chain.vader
    (1/1) [  GIVEN] Some imaginary filetype
    (1/1) [EXECUTE] Check the results of running the chain
    (1/1) [EXECUTE] (X) The final callback was not called
  Success/Total: 0/1
```

There is a travis log showing the failure on my PR #411 branch [here](https://travis-ci.org/w0rp/ale/builds/214740670). But I can reproduce on the upstream master as well.

**Comment by lucaskolstad** [comment]
In fact, the master build failed when my README change was merged in it looks like! Despite the change passing checks when I pushed it.

[Here](https://travis-ci.org/w0rp/ale/builds/214470141) is the travis log showing the same test case failing on the tests triggered by that merge.

**Comment by w0rp** [comment]
I believe I have fixed this now, but if this happens again, I'll re-open this issue. I believe the issue was caused by not being able to read data from stdin when the Vader tests were being run from inside of the docker image when the `echo` commands just so happened to run _before_ Vader had finished writing its output to the terminal... or something like that. The commands in that test file don't need to read from stdin at all, so that was easy to fix.
