### ISSUE TITLE
Feature request: ALE should prefer buffer-local variables over global variables (helpful for dynamic linter configuration)

### ISSUE THREAD

**Issue by smkent** [w0rp/ale#427]
### Background

I'm trying out ALE as a replacement for [Syntastic](https://github.com/vim-syntastic/syntastic).

I work with both Python 2 and 3, and I need ALE to select the correct version of `flake8` to use based on the file I'm working in. As suggested by the ALE documentation, I can set the executable and arguments used to invoke `flake8` as follows:

```vim
let g:ale_python_flake8_executable = 'python3'   " or 'python' for Python 2
let g:ale_python_flake8_args = '-m flake8'
```

I'd rather do this automatically, e.g. by parsing the shebang line (shebang parsing borrowed from Syntastic):

```vim
function! BufferParseShebang()
    let l:line = getline(1)
    if line =~# '^#!'
        let l:line = substitute(line, '\v^#!\s*(\S+/env(\s+-\S+)*\s+)?', '', '')
        let l:exe = matchstr(line, '\m^\S*\ze')
        let l:args = split(matchstr(line, '\m^\S*\zs.*'))
        return { 'exe': l:exe, 'args': l:args }
    endif
    return { 'exe': '', 'args': [] }
endfunction

function! ALEPythonVersionDetect()  " {{{
    let l:shebang_info = BufferParseShebang()
    if l:shebang_info['exe'] =~# '\m\<python[2-3]'
        let g:ale_python_flake8_executable = l:shebang_info['exe']
        let g:ale_python_flake8_args = '-m flake8'
    endif
endfunction  " }}}
augroup ale_python_detect
    autocmd!
    autocmd filetype python call ALEPythonVersionDetect()
augroup END
```

### Problem

The above code correctly sets the version of Python to use with `flake8` when I open a new file, but the linter settings are stored as global variables in vim. If I open a file written in one version of Python and another file written in a different version of Python, ALE won't select the correct linter to use for each file (since the settings are global).

To illustrate this:
* Put the above chunk of code in your `.vimrc`
* Place the following in a file called `py2`:
```python
#!/usr/bin/env python2
print 'test in python 2'
```
* Place the following in a file called `py3`:
```python
#!/usr/bin/env python3
print 'test in python 3'
```
* Open `py2`: `vim py2`. Note that ALE correctly shows no `flake8` errors.
* Open a new split with `py3`. Note that ALE correctly shows an error about the invalid `print` statement syntax (since Python 3 requires parentheses with `print`).
* Navigate back to the original split with `py2`. Note that ALE shows an error about the `print` statement, since the global settings for `flake8` now invoke it with `python3`.

### Solution

This problem would be solved if ALE supported reading linter settings from buffer-local variables, e.g. `b:ale_python_flake8_executable`, etc. Syntastic supports this behavior which makes working with different versions of Python easy using similar configuration as above, as each buffer has its own settings for invoking `flake8`.

ALE should be updated to prefer reading settings from buffer-local variables (`b:`), and fall back to the global (`g:`) variable of the same name if the buffer-local variable has no value.

**Comment by w0rp** [comment]
Sure, why not? Also, parsing of the shebang should probably be implemented too. A similar thing has been done already for shell scripts. I'd open a separate issue for that.

One complication is that the handlers for when callbacks for commands are fired can happen from a different buffer from the one you scheduled linting for. I recommend using 'getbufvar' when implementing this.

Another thing to bear in mind is that ALE has been setting default values for globals. I wanted to set defaults so you can always use `:echo` to see what the current value is. I suppose defaults should be set in the same way for buffer variables.

One implementation could look like `ale#Var('name', a:buffer, s:)`, which would check `getbufvar(a:buffer, ale_name)`, `g:ale_name`, then get a default from the `s:` variable you passed before, remembering to always set defaults​ when either is undefined.

Then again, it might not be worth setting default for buffer variables at all, as there's no guarantee variables will be set, even after linters run, and it's purely just so you can echo the default value. If they aren't set, you can also print the overrides in `:ALEInfo` more easily. So `ale#Var(a:buffer, 'name')` is probably better, taking the default value from the global instead, without setting the buffer variable. That should also be easier to implement. (Just `sed` every current use of variables in the dir besides the first level of indentation.)

All officially supported linters will have to be changed to using callbacks instead of strings for things when they use variables. They ought to be that way anyway. There are a few variables which still need to be renamed. I think those older ones should only be taken from global scope, and the newer variables should be preferred. I might fix the latter first, the former second, and then tackle this issue afterwards.

I recommend implementing this for linter options first, and considering global options second. There might be some global options where they won't make sense as buffer variables.

There are my morning thoughts!

**Comment by adriaanzon** [comment]
Buffer-local variables would also be really useful for disabling the `shellcheck` linter on scripts that only set variables, because you will get errors saying that the variables appear unused.

Examples of these scripts would be PKGBUILDs and dotenv files.

**Comment by w0rp** [comment]
I have now implemented buffer variable overrides for all linter options. I'll add some documentation for this behaviour tomorrow.

**Comment by w0rp** [comment]
I'll leave a comment here to remind myself. `:ALEInfo` needs to be updated to also output any buffer-local overrides that are set.

**Comment by w0rp** [comment]
Now linters and aliases can be configured with buffer-local variables. ALE will look at the buffer-local Dictionary values for keys first, then the global Dictionary values, and then default Dictionary values.

**Comment by w0rp** [comment]
I reckon enough options are supported in each buffer now. If any more are wanted, issues can be opened for them.
