### ISSUE TITLE
Clear errors immediately on change (implementation in description)

### ISSUE THREAD

**Issue by lericson** [w0rp/ale#441]
Typically, the line numbers become meaningless pretty much as soon as you start editing your code. For this reason I think it might be a better approach to clear them upon change.

There was no such feature, indeed, there's not even a feature to remove a buffer's linting results -- so here is my take:

```vim
fun! ALEClearBuffer(buffer)
  if get(g:, 'ale_enabled') && has_key(get(g:, 'ale_buffer_info', {}), a:buffer)
    call ale#engine#SetResults(a:buffer, [])
    call ale#cleanup#Buffer(a:buffer)
  endif
endfun

augroup UnALE
  autocmd!
  autocmd TextChanged,TextChangedI,InsertEnter,InsertLeave * call ALEClearBuffer(bufnr('%'))
augroup END
```

**Comment by w0rp** [comment]
This could be supported via an option. I'd leave it off by default. I suspect most users expect the errors and warnings to stay there until results come back from another lint cycle.

If this is going to be implemented, I suggest keeping the sign gutter open until after the next lint cycle completes. That will stop the text on the text on the screen from moving left and right too much when you have the option for keeping the gutter open all the time off.

I also suggest keeping the window for quick fix or loclist open until linting is completed again, even though items have been removed, or that will cause the text to move up and down too much otherwise.

**Comment by lericson** [comment]
Agreed, you'd want this with the permanent gutter option. By the way, is it possible to make it so that it opens immediately on launch instead of after the first linting pass?

Also not sure how this should work with respect to the qf/loclist -- perhaps makes most sense to clear them as well. Which is status quo.

Perhaps the clear command can be integrated into the code but the settings I use can be a FAQ entry?

- Ludvig

**Comment by w0rp** [comment]
Yeah, I've thought about opening the gutter straight away, if that option is on. That could be accomplished by setting up the dummy sign as soon as ALE loads and on each buffer load.

I think it makes sense to clear everything, and of course there would be a function available for doing it, probably in the `cleanup` namespace. The trick is to not close the loclist window automatically until after linting is done again.

**Comment by w0rp** [comment]
ALE now removes problems for different linters as soon as they return new results, and closes the sign column and so on when ever thing is done. This should be sufficient.
