### ISSUE TITLE
The signs are not updated

### ISSUE THREAD

**Issue by KabbAmine** [w0rp/ale#46]
Is it just for me or what? Starting from 6754b9f1f8b0, the signs are not updated.

![ale](https://cloud.githubusercontent.com/assets/5658084/19123181/b7a86470-8b3e-11e6-8177-5de555fac6e3.gif)

You can see in the gif above that even after correcting the error, the sign is still there.
Reverting back to aebf8e01963ce86040aa3571a4b2f5cab3516eb2 make the signs work as expected.

**Comment by w0rp** [comment]
Hmm, I tried the example above myself just now with Vim 8 and NeoVim, and I can't see the same problem. Have you tried using the latest code? I might have committed a bug and fixed it again.

**Comment by w0rp** [comment]
For the file which has the problem, could you paste the output of `:echo ale#sign#FindCurrentSigns(bufnr('%'))` when there are signs being displayed (correctly) and also the output of `:sign place`? Maybe there is a bug with the function which looks for the current signs I haven't spotted yet.

**Comment by deathmaz** [comment]
Hi guys, i have a feedback on this issue
Yesterday i left this comment https://github.com/w0rp/ale/issues/23#issuecomment-251504337 , the screencast was recorder on my home laptop.
Today in the morning i tried the plugin on my work laptop and everything worded fine so i thought that the issue was fixed.
But now i'm trying the plugin on my home laptop again and it doesn't work, the signs are not beign updated after the error was corrected.

I recorded a screencast with output of `:echo ale#sign#FindCurrentSigns(bufnr('%'))` and `:sign place`
https://asciinema.org/a/74xgodwysxs2kid971u9xrb71
`строка` means `line`
`имя` means `name`

**Comment by w0rp** [comment]
Oh! It looks like the options are translated into Russian there. I had no idea Vim translated the name of some options like that. That explains why it can't parse the sign IDs for you. I'll see if I can adjust the regex to account for that.

**Comment by w0rp** [comment]
I just pushed a commit with some new regex for parsing the sign IDs. Pull that and see if it is working now. I noticed that it was redundantly setting the dummy signs over and over again, so I made it only set at most one dummy.

**Comment by deathmaz** [comment]
Thank you! But i can try this later in the evening when i get back home.
For the moment everything works fine on my work computer

**Comment by KabbAmine** [comment]
Good catch :+1:  It was related to the used language (Mine is french).
Now, it works as it should.

Let's wait for @deathmaz confirmation before closing the issue.

**Comment by w0rp** [comment]
Yeah, let's wait for @deathmaz to check his instance of Vim at home. Thanks for pointing out the issue and the information guys. I wouldn't have caught that on my British English machines.

**Comment by deathmaz** [comment]
Checked, everything works fine! 👍

**Comment by w0rp** [comment]
Nice. Thanks for checking! Cheers, guys. :beers:
