### ISSUE TITLE
Can't `ALEFix` with nested ESLint configs

### ISSUE THREAD

**Issue by alexlafroscia** [w0rp/ale#634]
I've noticed that `:ALEFix` doesn't seem to work when it's within a directory with a custom ESLint config.

I made an example project that shows the problem:

[eslint-ale-fix-bug.zip](https://github.com/w0rp/ale/files/1058718/eslint-ale-fix-bug.zip)

If you `yarn install` (or `npm install`) in that project and go to the `double-quote-file.js`, change the double-quoted string to single-quotes and `:ALEFix`, it should turn them back into double quotes. That's, of course, the desired behavior.

If you open the `single-quote-file.js`, however, and change those single quotes to double quotes, then `:ALEFix`, it does not automatically fix the file despite reporting the double quotes as an error.

**Comment by w0rp** [comment]
This is because of a limitation in ESLint.

You can nest configuration files if you do not specify a configuration file explicitly, but the filename has to be on or beneath a directory where the configuration file lives. You can specify `--stdin-filename`, but you can't fix files when passing in input via stdin. You and specific the configuration file location explicitly and fix a temporary file, but then you can't use nested configuration files.

For this to be supported, ESLint will have to be changed to support one of the following.

1. Allow files passed via stdin to be fixed, by outputting the file with changes to stdout. (Like `autopep8` does.)
2. Allow configuration files set explicitly to search upwards for root configuration files.

The other option is that ALE could be set to only fix JavaScript files with ESLint when you save files, but that would suck and be less useful.

My recommendation for now is to use `extends` instead of nested configuration files. Restructure your project so you have a base configuration file, and two other configuration files which are both root configuration files which extend the base configuration file. That will work.

**Comment by alexlafroscia** [comment]
Huh! I'll try out those configuration changes and see if that fixes that's going on.

**Comment by alexlafroscia** [comment]
Yup! That works. Should I close this issue, or leave it open?

**Comment by w0rp** [comment]
I added this information to the online documentation. See `:help ale-eslint-nested-configuration-files`.

**Comment by alexlafroscia** [comment]
Awesome, thanks so much for the help!
