### ISSUE TITLE
 How to use the standard check html JavaScript code inside

### ISSUE THREAD

**Issue by dumuzhou** [w0rp/ale#672]
How to use the standard check html JavaScript code inside

**Comment by w0rp** [comment]
I can't recommend anything for `standard`, but for ESLint there is an HTML plugin. 

https://github.com/BenoitZugmeyer/eslint-plugin-html

If you change your filetype to `javascript.html`, then you might be able to run eslint on HTML files.

**Comment by dumuzhou** [comment]
Use the standard -- plugin html can detect html inside the javascript code, but in the html file type to how to use the standard -- plugin html ?

**Comment by dumuzhou** [comment]
package.json  add
```
{
  "standard": {
    "plugins": [ "html" ]
  }
}
```
this is okay too
But did not take effect in ale

**Comment by dumuzhou** [comment]
```
let g:ale_linters = {
\   "javascript": ["standard"],
\   "css": [],
\   "html": ["standard"]
\}
let g:ale_linter_aliases = {'html': ['javascript']}
let g:ale_javascript_standard_options = "--plugin html"
```
Also can not detect the HTML inside the JavaScript code

**Comment by dumuzhou** [comment]
@w0rp

**Comment by w0rp** [comment]
I'm not sure myself. This isn't something I have configured before.

**Comment by dumuzhou** [comment]
think you

**Comment by joeycozza** [comment]
@dumuzhou 
So I'm just using eslint, not standard, but I got eslint working for javascript inside .html files in vim.
w0rp mentioned in his comment to set the filetype to javascript.html. In the README, it shows exactly how to do this. (using jsx instead of html).

After I added this to my vimrc, vim's syntax highlighting was better for .html files with javascript in them, and ale automatically started working in .html files. I didn't even need to add `html: ['eslint']` in the ale_linters variable (since it recognized it as a javascript filetype I assume).

```vim
augroup FiletypeGroup
    autocmd!
    au BufNewFile,BufRead *.html set filetype=javascript.html
augroup END
```

Have you already tried that?
