### ISSUE TITLE
Flow does not work on windows

### ISSUE THREAD

**Issue by robarnold** [w0rp/ale#776]
I'm using Flow 0.45.0. It looks like the fix in 7ce960ae519e97e26e3c99c4faebe9d5290b487f which added `; echo.` to workaround a newline problem seems to have broken Flow on Windows. If I remove the `add_newline: 1` line from flow.vim, I can see errors in Vim again. If I run the command that ALE is running [1], it looks like Flow is trying to parse `; echo.` instead of `cmd`, so it prints out usage information and returns an error.

[1] `cmd /c flow check-contents --respect-pragma --json --from ale <redacted-file-path> < <redacted-file-temp-path>; echo.`

**Comment by w0rp** [comment]
This was easy to fix.

```diff
-\   'add_newline': 1,
+\   'add_newline': !has('win32'),
```

That's there for Unix because `flow` does not return the JSON output with a newline character at the end of the output. As a result, if you don't add the newline character, no lines of output are read in Vim.

I plan on seeing if it's possible to get Vim to read the last line of output from a job which does not contain a newline character at the end. Then the temporary `add_newline` option can be removed.
