### ISSUE TITLE
Please how to close ale auto popup quickfix window when I save the file

### ISSUE THREAD

**Issue by DemonCloud** [w0rp/ale#833]
<img width="1060" alt="screen shot 2017-08-08 at 9 24 07 am" src="https://user-images.githubusercontent.com/7436361/29052249-71d465e6-7bae-11e7-94fe-68c865f719b8.png">

**Comment by w0rp** [comment]
I broke that only hours ago for #271. I have fixed this now.

The problem arose because any comparison between `0` (the option being off) and most strings like `'on_save') (a new option) returns `1`, because of VimL's rules for the equality operator. I've seen this kind of bug before, so I just added `type(x) == type('') && ...`
