### ISSUE TITLE
An issue with eslint, and possible javascript in general

### ISSUE THREAD

**Issue by aaron-goshine** [w0rp/ale#849]
Complaining that there is an extra semicolon and on removing the semicolon, it then complain that there is a missing semicolon.

while my global eslintrc is configure to always keep the semicolons in.

**question:** 
Is there a way to show all the  error and warning in the quick fix window like syntactic, with the ability to jump to the line number where the fix is need.

**Comment by w0rp** [comment]
There might be a local ESLint configuration file which is configured different from your global one. You should check your configuration files and ask for help with ESLint on Stack Overflow, or similar. See `:help g:ale_set_quickfix` and `:help ale-navigation-commands` for your other two questions. Although I recommend using loclist instead of quickfix.
