### ISSUE TITLE
HTML5 tags not recognized

### ISSUE THREAD

**Issue by garand** [w0rp/ale#878]
I'm seeing errors with my HTML5 tags not being recognized.

<img width="675" alt="screen shot 2017-08-26 at 4 41 06 pm" src="https://user-images.githubusercontent.com/82437/29744968-a5d97af6-8a7d-11e7-8bc8-0e17dbef4c89.png">

Also, I use JS components from time to time and they have custom tag names. So my question is two-fold, is there a way to make it recognize valid HTML5 tags, and separately, is it possible to disable errors for invalid tag names all together?

Thanks!

**Comment by w0rp** [comment]
There might be some way to configure the program to recognise different doctypes or to allow more HTML tags. Find out which program is returning these messages by checking `:ALEInfo` and consult the documentation for each tool.

I use a Pug linter at work which can be configured to allow custom tags or additional attributes. So that had to be configured to do that.

**Comment by ash886h** [comment]
ahah

**Comment by keithamus** [comment]
The problem here is that `/usr/bin/tidy` - the `tidy` included in mac osx is quite old:

> HTML Tidy for Mac OS X released on 31 October 2006 - Apple Inc. build 15.18.1

There is a more recent version available in [homebrew](https://github.com/Homebrew/) called `tidy-html5` (it writes to `/usr/local/bin/tidy` so is a drop-in replacement):

```sh
brew install tidy-html5
```

This fixed the problem for me.

**Comment by w0rp** [comment]
Sounds like that comment holds the answer.

**Comment by marcusandre** [comment]
Yes. This works perfeclty for me now. :)
