### ISSUE TITLE
ghc-mod can take input from stdin

### ISSUE THREAD

**Issue by purpleP** [w0rp/ale#880]
I'm not using this plugin anymore, so won't provide pull request, but I've found that `ghc-mod` can take input from `stdin`.

 `cat src/Changes.hs  <(echo '\x04\x0A') | ghc-mod check src/Changes.hs --map-file 'src/Changes.hs'`

For some reason it waits for `\x04\x0A` sequence to mark the end of file and just using cat will produce error. But if you append this sequence to the file content it works just fine.

**Comment by w0rp** [comment]
Those characters are the EOT or "end of transmission" characters and a line feed.

Thank you for the information. The temporary files being used at the moment work just fine, so nothing will be changed for the moment. This could be useful if sending buffer data via stdin is judged to be useful.

Not all versions of Vim are capable of sending buffer data directly to jobs. It can't be done in any stable NeoVim version I know of, and it only works on some platforms for Vim 8. Notably, Windows and MacVim versions have had trouble with sending buffer data via stdin to jobs directly. For this reason, ALE just uses `< TEMPORARY_FILE_NAME_HERE` at the end of commands which receive buffer data via stdin for all versions at the moment, so you a temporary file is generated either way.

I might consider adding an option, which will be off by default, so sending buffer data directly to jobs for in Vim 8, in a future version of the plugin.

**Comment by purpleP** [comment]
@w0rp Oh, thanks, I didn't know about vim issues. I use latest neovim and this works for me just fine on linux.
```
let l:Lint = function('lint#StartLint', [a:CmdMaker])
let opts = {'on_exit': function('lint#CheckPending', [a:fname, l:Lint])}
let l:jobid = jobstart(a:CmdMaker(a:fname), opts) 
call jobsend(l:jobid, join(getbufline(bufnr(a:fname), 1,'$'), "\n"))
call jobclose(l:jobid, 'stdin')
```

I'm developing a linting plugin that addresses some issues I have with your linting plugin. I will describe my approach, so that maybe if your interested in it you will integrate this into your plugin. The issues are:

1. Using signs are too intrusive for me.

- Always showing sign column takes space even if there are no errors. Most of the time code doesn't have errors, right? So most of the time this space is wasted.
- Showing sign column only when there are errors makes annoying jumpiness when errors are appearing/disappearing quickly.
- Sign column doesn't give you any information about errors that aren't visible on the screen, so sooner or later you would need to open quickfix if you want to examine more errors.

2. Highlighting errors doesn't work properly in some linters (remember that pylint issue I raised?).

3. This is the most important. Not in any plugin, not in any IDE you can't ignore errors reliably. Using comments is also too intrusive for me, but more importantly they can hide new errors from you if the error code is the same, but the reason for it is different. If this could be done maybe highlighting errors would be that bad, but if highlighting sticks even if there is no error - that's too intrusive.

I thought about it for a while and came up with simple heuristic that seems to be working pretty fine for me.
1. Show errors in quickfix window, no signs, no highlights.
2. If I already saw and error and closed quickfix window - don't  show it to me unless errors have changed.
3. If errors changed to the state where there is no errors - close quickfix automatically.

Right now I use special folder in `/tmp` directory to save linting results to know if they have changed, but I guess this could be done without it by examining quickfix maybe.

**Comment by purpleP** [comment]
@w0rp Oh, I also found out about why the error messages have been truncated all this time. `ghc-mod` outputs null characters. I solved it with adding `sed 's/\000'//p' to it. This wouldn't work on windows, so maybe you could allow it optionally on unix or parse text manually.

**Comment by w0rp** [comment]
There are a few points to tackle, so I'll give you some bullet points.

- For ALE, the default behaviour is to show signs, and only show the sign column when there are signs to show. You can either disable the signs completely, or use a setting so the sign column stays open, depending on your preferences.
- For errors no in the same file, linters can be configured to display errors from other files by setting up the `filename` key. Someone is currently attempting to set this up for one of the Haskell linters, but he hasn't figured out the best way to resolve the paths returned in the output yet. Solving this problem is easier when the programs can output absolute paths to files.
- The null byte thing you mention sounds useful. That might be an easier way to fix the issue of having to join lines together, if someone can create a pull request with it, with some tests.

I think generally, there are answers available for the questions you are asking. I recommend reading the documentation for ALE first. Most questions along the lines of, "I like this, but I don't want that" can be answered with existing options.

**Comment by purpleP** [comment]
@w0rp I think you don't understand my point (maybe I'm communicating it very well).

- I know how ALE behaves. That's exactly the point. Showing signs only when there are errors creates problems (jumpiness), not showing them also creates problems (not being able to detect errors right away), showing them always wastes space.
- I don't think I written anything about displaying errors from different files.
- I don't see what are the answers to the problems I'm talking about, no. The two main problems are detecting errors right away without introducing vertical jumpiness and ignoring errors.

**Comment by w0rp** [comment]
If you don't like the jumpiness, then use `let g:ale_set_signs = 1` or `let g:ale_sign_column_always = 1`.

Take the time to read the documentation and think before you speak.

**Comment by purpleP** [comment]
@w0rp Have you noticed that I mentioned twice, that always showing sign column wastes space?

**Comment by w0rp** [comment]
Then disable the sign column. If you don't want signs, turn them off.

**Comment by purpleP** [comment]
@w0rp Have you noticed that I've said that disabling signs would make impossible to see errors right away?

**Comment by w0rp** [comment]
I honestly don't know what you want, and you're not being very constructive in your comments. If you have a proposal for how to improve the plugin, then open an issue or a pull request, and I and others can look at it. If you just plain don't like the plugin, then don't use it. I'm going to lock this thread now, because you are making an ass of yourself.

**Comment by w0rp** [comment]
If anyone is interested, if you don't want signs or highlights in ALE, you can easily disable them completely if you read the documentation. Please read the documentation carefully. Please also consider that there might be more to solving a problem than you or anyone has considered so far.
