### ISSUE TITLE
A file linter should not be run if it's still running

### ISSUE THREAD

**Issue by JelteF** [w0rp/ale#937]
I'm using `gometalinter` without the `--fast` option. This is uses a lot of CPU, which is usually not an issue. However, when I save a couple of times in quick succession the linter is fired up each time. Even when the previous run is not finished yet. This causes an incredible amount of load. Is there a way to say it shouldn't be fired up if it's still running or to kill the old linter before spawning the new one (which would be even better)?

**Comment by w0rp** [comment]
Are you using NeoVim? ALE will kill the process, but NeoVim is buggy and doesn't actually kill the process. It'll be fixed in the next NeoVim version.

**Comment by JelteF** [comment]
Yes, I'm using neovim (sorry for not mentioning it). Is the fix already on git master of neovim? Because then I'll just install that one.

**Comment by JelteF** [comment]
Hmm this actually seems to be an issue with gometalinter not killing it's linters when you kill the process. I'll file a bugreport there.

**Comment by w0rp** [comment]
The bug might be on NeoVim. I don't think it's on master yet. The issue is here: https://github.com/neovim/neovim/issues/6530

The bug is that processes aren't created inside of process groups which can be killed to then kill any child processes, which is what Vim 8 does. So that can be a problem with NeoVim, the program, or both.
